name: Bug report
description: Something isn't working
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "Describe the bug."
    validations:
      required: true
