name: Feature request
description: Suggest an improvement or new capability
type: Feature
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "Describe the feature."
    validations:
      required: true
